Safety.Web/Controllers/DashboardController.cs
using Safety.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Safety.Application.Searches;
using Safety.Application.Filters;
using Safety.Domain.Constants;
using Safety.Domain.Entities;
using System.Text.Json.Serialization;
using System.Text.Json;
using AutoMapper;
using Safety.Domain.Interfaces.Services;
using Safety.Domain.Interfaces;
using Microsoft.Data.SqlClient;

namespace Safety.Web.Controllers
{
    public class DashboardController : BaseController
    {
        private readonly IFuncionarioService _funcionarioService;

        public DashboardController(
            IMapper mapper,
            IAppLogger logger,
            IFuncionarioService funcionarioService) : base(logger, mapper)
        {
            _mapper = mapper;
            _logger = logger;
            _funcionarioService = funcionarioService;
        }

        public async Task<IActionResult> Index(int? id, bool state = false)
        {
            FuncionarioSearch funcionarioSearch = new FuncionarioSearch();
            IEnumerable<Funcionario> funcionarios = null;

            DashboardViewModel dashboardViewModel = new DashboardViewModel();

            dashboardViewModel.TotalFuncionarios = await _funcionarioService.CountAsync(c => c.FuncionarioId > 0);
            dashboardViewModel.FuncionariosAtivos = await _funcionarioService.CountAsync(c => c.Ativo == true);
            dashboardViewModel.FuncionariosDesativados = await _funcionarioService.CountAsync(c => c.Ativo == false);
            dashboardViewModel.FuncionariosRecentes = await _funcionarioService.CountAsync(c => c.Edicao >= DateTime.Now.AddDays(-30));

            ViewBag.FuncionariosTotais = dashboardViewModel.TotalFuncionarios;
            ViewBag.FuncionariosAtivos = dashboardViewModel.FuncionariosAtivos;
            ViewBag.FuncionariosDesativados = dashboardViewModel.FuncionariosDesativados;


            funcionarios = await _funcionarioService.GetByTakeLastRelatedAsync(funcionarioSearch.TakeLast);

            List<FuncionarioViewModel> funcionarioViewModels = _mapper.Map<IEnumerable<Funcionario>, IEnumerable<FuncionarioViewModel>>(funcionarios).ToList();

            funcionarioSearch.Itens = funcionarioViewModels;
            funcionarioSearch.DashboardViewModel = dashboardViewModel;

            _logger.LogInformation(FuncionarioConst.LOG_INDEX, User.Identity.Name ?? DefaultConst.USER_ANONYMOUS, DateTime.Now);

            return View(funcionarioSearch);
        }
    }
}

Safety.Web/Controllers/FuncionariosController.cs
using Safety.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Safety.Domain.Interfaces.Services;
using AutoMapper;
using Safety.Domain.Interfaces;
using Safety.Domain.Entities;
using Safety.Domain.Constants;
using System.Text.Json.Serialization;
using System.Text.Json;
using Safety.Application.Searches;
using Safety.Application.Filters;
using Safety.Domain.Services;
using Safety.Domain.Resources;
using Safety.Web.Extensions;
using Microsoft.AspNetCore.Mvc.Rendering;
using Safety.Domain.Enums;

namespace Safety.Web.Controllers
{
    public class FuncionariosController : BaseController
    {
        private readonly IFuncionarioService _funcionarioService;
        private readonly ICargoService _cargoService;
        private readonly IFeriasService _feriasService;

        public FuncionariosController(
            IMapper mapper,
            IAppLogger logger,
            IFuncionarioService funcionarioService,
            ICargoService cargoService,
            IFeriasService feriasService) : base(logger, mapper)
        {
            _mapper = mapper;
            _logger = logger;
            _funcionarioService = funcionarioService;
            _cargoService = cargoService;
            _feriasService = feriasService;
        }

        public async Task<IActionResult> Index(int? id, bool state = false)
        {
            ViewBag.SelectListCargos = await Task.Run(() => SelectListCargos());

            FuncionarioSearch funcionarioSearch = new FuncionarioSearch();
            IEnumerable<Funcionario> funcionarios = null;

            if (!state)
            {
                TempData[DefaultConst.TEMPDATA_FILTERSTATE] = null;
            }

            if (!string.IsNullOrWhiteSpace(TempData[DefaultConst.TEMPDATA_FILTERSTATE]?.ToString()))
            {
                funcionarioSearch = JsonSerializer.Deserialize<FuncionarioSearch>(TempData[DefaultConst.TEMPDATA_FILTERSTATE]?.ToString());
                if (funcionarioSearch.HasFilter)
                {
                    funcionarios = await _funcionarioService.GetByTakeLastRelatedAsync(funcionarioSearch.TakeLast);
                }
                else
                {
                    FuncionarioFilter filter = _mapper.Map<FuncionarioFilterViewModel, FuncionarioFilter>(funcionarioSearch?.Filter);
                    funcionarios = await _funcionarioService.GetByFilterRelatedAsync(filter);
                }

                if (state)
                {
                    TempData[DefaultConst.TEMPDATA_FILTERSTATE] = JsonSerializer.Serialize(funcionarioSearch, new JsonSerializerOptions() { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull });
                }
            }
            else
            {
                if (id != null)
                {
                    Funcionario funcionario = await _funcionarioService.GetByIdRelatedAsync(id.GetValueOrDefault(-1));
                    if (funcionario != null)
                    {
                        funcionarios = new List<Funcionario>() { funcionario };
                    }
                }
                else
                {
                    funcionarios = await _funcionarioService.GetByTakeLastRelatedAsync(funcionarioSearch.TakeLast);
                }
            }

            List<FuncionarioViewModel> funcionarioViewModels = _mapper.Map<IEnumerable<Funcionario>, IEnumerable<FuncionarioViewModel>>(funcionarios).ToList();

            funcionarioSearch.Itens = funcionarioViewModels;

            _logger.LogInformation(FuncionarioConst.LOG_INDEX, User.Identity.Name ?? DefaultConst.USER_ANONYMOUS, DateTime.Now);

            return View(funcionarioSearch);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(FuncionarioSearch funcionarioSearch)
        {
            ViewBag.SelectListCargos = await Task.Run(() => SelectListCargos());

            IEnumerable<Funcionario> funcionarios;

            funcionarioSearch.HasFilter = false;

            if (funcionarioSearch.HasFilter)
            {
                funcionarios = await _funcionarioService.GetByTakeLastRelatedAsync(funcionarioSearch.TakeLast);
            }
            else
            {
                FuncionarioFilter filter = _mapper.Map<FuncionarioFilterViewModel, FuncionarioFilter>(funcionarioSearch?.Filter);
                funcionarios = await _funcionarioService.GetByFilterRelatedAsync(filter);
            }

            List<FuncionarioViewModel> funcionarioViewModels = _mapper.Map<IEnumerable<Funcionario>, IEnumerable<FuncionarioViewModel>>(funcionarios).ToList();

            funcionarioSearch.Itens = funcionarioViewModels;

            TempData[DefaultConst.TEMPDATA_FILTERSTATE] = JsonSerializer.Serialize(funcionarioSearch, new JsonSerializerOptions() { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull });

            _logger.LogInformation(FuncionarioConst.LOG_INDEX, User.Identity.Name ?? DefaultConst.USER_ANONYMOUS, DateTime.Now);

            return View(funcionarioSearch);
        }

        public async Task<IActionResult> ResumoFuncionario(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            IEnumerable<Funcionario> funcionarios = await _funcionarioService.GetByQueryRelatedAsync(w => w.FuncionarioId == id.GetValueOrDefault(-1));

            Funcionario funcionario = funcionarios.FirstOrDefault();

            if (funcionario == null)
            {
                return NotFound();
            }

            //AutoMapper
            var funcionarioViewModel = _mapper.Map<Funcionario, FuncionarioViewModel>(funcionario);
            int DiasDeTrabalho = 22;

            funcionarioViewModel.ValeAlimentacao = funcionarioViewModel.DiariaVA * DiasDeTrabalho;
            funcionarioViewModel.ValeRefeicao = funcionario.Salario * (decimal)0.06;
            funcionarioViewModel.ValeTransporte = funcionario.Salario * (decimal)0.06;

            funcionarioViewModel.MesReferencia = DateTime.Now.AddMonths(-1);

            _logger.LogInformation(FuncionarioConst.LOG_DETAILS, User.Identity.Name ?? DefaultConst.USER_ANONYMOUS, DateTime.Now);

            return View(funcionarioViewModel);
        }

        public async Task<IActionResult> ResumoFuncionarioPrint(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IEnumerable<Funcionario> funcionarios = await _funcionarioService.GetByQueryRelatedAsync(w => w.FuncionarioId == id.GetValueOrDefault(-1));

            Funcionario funcionario = funcionarios.FirstOrDefault();

            if (funcionario == null)
            {
                return NotFound();
            }

            //AutoMapper
            var funcionarioViewModel = _mapper.Map<Funcionario, FuncionarioViewModel>(funcionario);
            int DiasDeTrabalho = 22;

            funcionarioViewModel.ValeAlimentacao = funcionarioViewModel.DiariaVA * DiasDeTrabalho;
            funcionarioViewModel.ValeRefeicao = funcionario.Salario * (decimal)0.06;
            funcionarioViewModel.ValeTransporte = funcionario.Salario * (decimal)0.06;

            funcionarioViewModel.MesReferencia = DateTime.Now.AddMonths(-1);

            _logger.LogInformation(FuncionarioConst.LOG_DETAILS, User.Identity.Name ?? DefaultConst.USER_ANONYMOUS, DateTime.Now);

            return View(funcionarioViewModel);
        }

        public async Task<IActionResult> CalculoFeriasCreate(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            IEnumerable<Funcionario> funcionarios = await _funcionarioService.GetByQueryRelatedAsync(w => w.FuncionarioId == id.GetValueOrDefault(-1));

            Funcionario funcionario = funcionarios.FirstOrDefault();

            //IEnumerable<Ferias> feriass = await _feriasService.GetByQueryRelatedAsync(w => w.FuncionarioId == id.GetValueOrDefault(-1));

            //Ferias ferias = feriass.FirstOrDefault();

            if (funcionario == null)
            {
                return NotFound();
            }

            FuncionarioViewModel funcionarioViewModel = _mapper.Map<Funcionario, FuncionarioViewModel>(funcionario);


            _logger.LogInformation(FuncionarioConst.LOG_DETAILS, User.Identity.Name ?? DefaultConst.USER_ANONYMOUS, DateTime.Now);

            return View(funcionarioViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CalculoFeriasCreate(int? id, FuncionarioViewModel funcionarioViewModel)
        {
            if (id == null)
            {
                return NotFound();
            }

            //AutoMapper
            var ferias = _mapper.Map<FeriasViewModel, Ferias>(funcionarioViewModel.Ferias);
            var funcionario = _mapper.Map<FuncionarioViewModel, Funcionario>(funcionarioViewModel);

            ferias.FuncionarioId = id;
            

            funcionario.Salario = funcionarioViewModel.SalarioFinal;
                
            #region Cálculos da Folha de Pagamento

            int DiasDeTrabalho = 22;
            double SalarioINSS = 0;
            decimal descontoIRRF = 0;
            double SalarioFuncionario = (double)funcionario.Salario;

            funcionarioViewModel.ValeAlimentacao = funcionarioViewModel.DiariaVA * DiasDeTrabalho;

            decimal totalFaixaUm = 0;
            decimal totalFaixaDois = 0;
            decimal totalFaixaTres = 0;
            decimal totalFaixaQuatro = 0;

            decimal descontoFaixaUm = 0;
            decimal descontoFaixaDois = 0;
            decimal descontoFaixaTres = 0;
            decimal descontoFaixaQuatro = 0;

            

            funcionario.INSS = totalFaixaUm + totalFaixaDois + totalFaixaTres + totalFaixaQuatro;

            #region Desconto Inss
            if (SalarioFuncionario <= 1320.00)
            {

Safety.Web/Controllers/ProfileController.cs
using Safety.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Safety.Domain.Interfaces.Services;
using AutoMapper;
using Safety.Domain.Interfaces;
using Safety.Domain.Constants;
using Safety.Domain.Entities;
using Safety.Application.Filters;
using Safety.Application.Searches;
using System.Text.Json.Serialization;
using System.Text.Json;

namespace Safety.Web.Controllers
{
    public class ProfileController : BaseController
    {
        private readonly IFuncionarioService _funcionarioService;

        public ProfileController(
            IMapper mapper,
            IAppLogger logger,
            IFuncionarioService funcionarioService) : base(logger, mapper)
        {
            _mapper = mapper;
            _logger = logger;
            _funcionarioService = funcionarioService;
        }

        public async Task<IActionResult> Index(int? id, bool state = false)
        {
            //FuncionarioSearch funcionarioSearch = new FuncionarioSearch();
            //IEnumerable<Funcionario> funcionarios = null;

            //if (!state)
            //{
            //    TempData[DefaultConst.TEMPDATA_FILTERSTATE] = null;
            //}

            //if (!string.IsNullOrWhiteSpace(TempData[DefaultConst.TEMPDATA_FILTERSTATE]?.ToString()))
            //{
            //    funcionarioSearch = JsonSerializer.Deserialize<FuncionarioSearch>(TempData[DefaultConst.TEMPDATA_FILTERSTATE]?.ToString());
            //    if (funcionarioSearch.HasFilter)
            //    {
            //        funcionarios = await _funcionarioService.GetByTakeLastRelatedAsync(funcionarioSearch.TakeLast);
            //    }
            //    else
            //    {
            //        FuncionarioFilter filter = _mapper.Map<FuncionarioFilterViewModel, FuncionarioFilter>(funcionarioSearch?.Filter);
            //        funcionarios = await _funcionarioService.GetByFilterRelatedAsync(filter);
            //    }

            //    if (state)
            //    {
            //        TempData[DefaultConst.TEMPDATA_FILTERSTATE] = JsonSerializer.Serialize(funcionarioSearch, new JsonSerializerOptions() { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull });
            //    }
            //}
            //else
            //{
            //    if (id != null)
            //    {
            //        Funcionario funcionario = await _funcionarioService.GetByIdRelatedAsync(id.GetValueOrDefault(-1));
            //        if (funcionario != null)
            //        {
            //            funcionarios = new List<Funcionario>() { funcionario };
            //        }
            //    }
            //    else
            //    {
            //        funcionarios = await _funcionarioService.GetByTakeLastRelatedAsync(funcionarioSearch.TakeLast);
            //    }
            //}

            //List<FuncionarioViewModel> funcionarioViewModels = _mapper.Map<IEnumerable<Funcionario>, IEnumerable<FuncionarioViewModel>>(funcionarios).ToList();

            //funcionarioSearch.Itens = funcionarioViewModels;

            //_logger.LogInformation(FuncionarioConst.LOG_INDEX, User.Identity.Name ?? DefaultConst.USER_ANONYMOUS, DateTime.Now);

            //return View(funcionarioSearch);

            _logger.LogInformation(FuncionarioConst.LOG_CREATE, User.Identity.Name ?? DefaultConst.USER_ANONYMOUS, DateTime.Now);

            FuncionarioViewModel funcionarioViewModel = await Task.Run(() => new FuncionarioViewModel());

            return View(funcionarioViewModel);
        }
    }
}

Safety.Web/Views/Shared/_DataTableScriptsPartial.cshtml
<script>

    $(document).ready(function () {

        var table = $('.datatables-table').DataTable(
            {
                dom: 'frtip', //Default Value: lfrtip
                language: {
                    url: '@Url.Content("~/")' + 'Portuguese-Brasil.json',
                },
                buttons: ['copy', 'csv', 'excel', 'pdf', 'print']
            });

        //copy
        $("#dataTableExportCopy").on("click", function () {
            table.button('.buttons-copy').trigger();
        });

        //excel
        $("#dataTableExportExcel").on("click", function () {
            table.button('.buttons-excel').trigger();
        });

        //print
        $("#dataTableExportPrint").on("click", function () {
            table.button('.buttons-print').trigger();
        });

        //pdf
        $("#dataTableExportPDF").on("click", function () {
            table.button('.buttons-pdf').trigger();
        });

    });

</script>

Safety.Web/Views/Shared/_DataTableScriptsPartialResponsive.cshtml
<script>

    $(document).ready(function () {

        var table = $('.datatables-table').DataTable(
            {
                responsive: true,
                dom: 'frtip', //Default Value: lfrtip
                language: {
                    url: '@Url.Content("~/")' + 'Portuguese-Brasil.json',
                },
                buttons: ['copy', 'csv', 'excel', 'pdf', 'print']
            });

        // Adicionar tooltips do Bootstrap para botões e links
        $('.datatables-table tbody').on('mouseenter', '[data-toggle="tooltip"]', function () {
            var title = $(this).attr('title');
            $(this).tooltip({
                title: title,
                placement: 'top',
                trigger: 'hover'
            });
            $(this).tooltip('show');
        });

        //copy
        $("#dataTableExportCopy").on("click", function () {
            table.button('.buttons-copy').trigger();
        });

        //excel
        $("#dataTableExportExcel").on("click", function () {
            table.button('.buttons-excel').trigger();
        });

        //print
        $("#dataTableExportPrint").on("click", function () {
            table.button('.buttons-print').trigger();
        });

        //pdf
        $("#dataTableExportPDF").on("click", function () {
            table.button('.buttons-pdf').trigger();
        });

    });

</script>

Safety.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="~/css/customWhite.css" data-skin="default">
    @*<link rel="stylesheet" href="~/css/theme-light.css" data-skin="lightTheme">*@
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />

    <link href="~/lib/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/responsive.bootstrap4.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

    <script>
        var skin = localStorage.getItem('skin') || 'default';
        var disabledSkinStylesheet = document.querySelector('link[data-skin]:not([data-skin="' + skin + '"])');
        // Disable unused skin immediately
        disabledSkinStylesheet.setAttribute('rel', '');
        disabledSkinStylesheet.setAttribute('disabled', true);
    </script>

</head>
<body>
    
    
    <div class="sidebar close">
        <div class="logo-details bg-primary shadow">
            <i><img src="~/img/RecrutaPlus.png" class="img-nav-icon" /></i>
        </div>
        <ul class="nav-links bg-white shadow text-primary">
            <li>
                <a asp-area="" asp-controller="Dashboard" asp-action="Index">
                    <i class="fa-solid fa-house text-primary"></i>
                    <span class="link_name">Dashboard</span>
                </a>
            </li>
            <li>
                <a asp-area="" asp-controller="Funcionarios" asp-action="Index">
                    <i class="fa-regular fa-address-card text-primary"></i>
                    <span class="link_name">Funcionarios</span>
                </a>
            </li>
            <hr class="hr-color  text-primary" />
            @*<li>
                <a asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="">
                    <i class="fa-regular fa-user"></i>
                    <span class="link_name">Perfil</span>
                </a>
            </li>*@
            @*<li>
                <a asp-area="" data-toggle="skin">
                    <i class="fa-solid fa-moon"></i>
                    <span class="link_name">DarkTheme</span>
                </a>
            </li>*@
            <li>
                <a asp-area="" data-bs-toggle="modal" data-bs-target="#modalSair">
                    <i class="fa-solid fa-arrow-right-from-bracket text-primary"></i>
                    <span class="link_name">Sair</span>
                </a>
            </li>
        </ul>
    </div>
    <section class="home-section">
        <header class="layout-header sticky-top bg-primary">
            <i class='bx bx-menu'></i>
        </header>
        <div class="home-content">
            <card class="w-100">
                @RenderBody()
            </card>
            
        </div>
        <footer class="layout-footer justify-content-center">
            <h6 class="text-primary mb-0 pl-4">&nbsp; developed by Gabriel Kennedy and Vinicius Ottoni <strong class="text-primary">@DateTime.Now.ToString("yyyy")</strong></h6>
        </footer>
    </section>
   

    <div class="modal fade " id="modalSair" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5 text-primary" id="staticBackdropLabel">Confirmar Saida?</h1>
                </div>
                <form asp-action="index" asp-controller="login" method="post">
                    <div class="modal-body">
                        <div class="d-flex gap-2">

                            <span>Você tem certeza que deseja <strong class="text-primary">deslogar?</strong></span>

                        </div>
                    </div>
                    <div class="modal-footer justify-content-end">
                        <button type="button" class="btn btn-dark" data-bs-dismiss="modal" aria-label="Close">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Logout</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="~/lib/chartjs/chart.min.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/popper.js/umd/popper.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>

    <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/dataTables.bootstrap4.min.js"></script>

    <script src="~/lib/datatables/dataTables.responsive.min.js"></script>
    <script src="~/lib/datatables/responsive.bootstrap4.min.js"></script>

    <script src="~/lib/datatables/js/dataTables.buttons.min.js"></script>
    <script src="~/lib/datatables/buttons.bootstrap4.min.js"></script>
    <script src="~/lib/datatables/js/buttons.html5.min.js"></script>
    <script src="~/lib/datatables/js/buttons.print.min.js"></script>
    <script src="~/lib/datatables/js/buttons.colVis.min.js"></script>

    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>

    <script>
        let arrow = document.querySelectorAll(".arrow");
        for (var i = 0; i < arrow.length; i++) {
            arrow[i].addEventListener("click", (e) => {
                let arrowParent = e.target.parentElement.parentElement;
                arrowParent.classList.toggle("showMenu");
            });
        }
        let sidebar = document.querySelector(".sidebar");
        let sidebarBtn = document.querySelector(".bx-menu");
        console.log(sidebarBtn);
        sidebarBtn.addEventListener("click", () => {
            sidebar.classList.toggle("close");
        });

    </script>

    @RenderSection("Scripts", required: false)

</body>
</html>

Safety.Web/Views/Shared/_LayoutPrint.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="~/css/customWhite.css" data-skin="default">
    @*<link rel="stylesheet" href="~/css/theme-light.css" data-skin="lightTheme">*@
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

    <script>
        var skin = localStorage.getItem('skin') || 'default';
        var disabledSkinStylesheet = document.querySelector('link[data-skin]:not([data-skin="' + skin + '"])');
        // Disable unused skin immediately
        disabledSkinStylesheet.setAttribute('rel', '');
        disabledSkinStylesheet.setAttribute('disabled', true);
    </script>

</head>
<body>
    
    
    
    <main class="auth">

        @RenderBody()

    </main><!-- /.auth -->
   

    <div class="modal fade " id="modalSair" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5 text-primary" id="staticBackdropLabel">Confirmar Saida?</h1>
                </div>
                <form asp-action="index" asp-controller="login" method="post">
                    <div class="modal-body">
                        <div class="d-flex gap-2">

                            <span>Você tem certeza que deseja <strong class="text-primary">deslogar?</strong></span>

                        </div>
                    </div>
                    <div class="modal-footer justify-content-end">
                        <button type="button" class="btn btn-dark" data-bs-dismiss="modal" aria-label="Close">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Logout</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="~/lib/chartjs/chart.min.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/popper.js/umd/popper.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>

    <script>
        let arrow = document.querySelectorAll(".arrow");
        for (var i = 0; i < arrow.length; i++) {
            arrow[i].addEventListener("click", (e) => {
                let arrowParent = e.target.parentElement.parentElement;
                arrowParent.classList.toggle("showMenu");
            });
        }
        let sidebar = document.querySelector(".sidebar");
        let sidebarBtn = document.querySelector(".bx-menu");
        console.log(sidebarBtn);
        sidebarBtn.addEventListener("click", () => {
            sidebar.classList.toggle("close");
        });

    </script>

    @RenderSection("Scripts", required: false)

</body>
</html>

Safety.Web/Views/Shared/_Layout_login.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="~/css/login.css">
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
        <div>
            @RenderBody()
        </div>

    <script>

    </script>
</body>
</html>

Safety.Web/Views/Shared/_TakeLastScriptsPartial.cshtml
<script>

    //Take
    $(document).on("change", "#modalFilterColumns input[type=text], input[type=date], input[time], input[number], input[datetime], input[datetime-local], select", function (e) {
        console.info(e);
        if(e.target.id != 'TakeLast'){
            $('#hasFilter').prop('checked', false);
            $('#multi-collapse').collapse('hide');
        }
    });

</script>